# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main, develop]

permissions:
  issues: write  # Permissão para criar issues
  pull-requests: write  # Permissão para interagir com PRs

jobs:
  test-ci:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run test
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - name: Awaiting Approval for Staging
        uses: hmarr/await-approval@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Staging
        if: success()
        run: echo "Deploying to Staging..."
  deploy-production:
    needs: [test-ci]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    concurrency: deploy-to-production
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: luizalexandrew
          minimum-approvals: 1
          timeout-minutes: 10
      - name: Gerar versão baseada na data, hora e minuto
        id: version
        run: |
          VERSION=$(date +'%Y%m%d%H%M')  # Exemplo: 202503171230
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - run: docker build -t setup-nodejs .
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: true
          tags: |
            luizalexandrew/la-ci-cd:latest
            luizalexandrew/la-ci-cd:${{ env.VERSION }}
